import gs_logo from "./gs_logo.jpg"
import korea_logo from "./korea_logo.png"
import happy_store from "./happy_store.webp"
import upload_area from "./upload_area.svg"
import essence from "./essence.jpg"
import anna_keibalo from "./anna-keibalo.jpg"
import elena_soroka from "./elena-soroka.jpg"
import maria_lupan from "./maria-lupan.jpg"
import valeriia_miller from "./valeriia-miller.jpg"
import { ClockFadingIcon, HeadsetIcon, SendIcon } from "lucide-react";
import profile_pic1 from "./profile_pic1.jpg"
import profile_pic2 from "./profile_pic2.jpg"
import profile_pic3 from "./profile_pic3.jpg"
import type { Store, Rating, Product, Address, Coupon, User, Order } from "@/types";

export const assets = {
    upload_area, essence, anna_keibalo, elena_soroka, maria_lupan, valeriia_miller,
    gs_logo, korea_logo,
}

export const categories = ["Skincare", "Makeup", "Hair Care", "Body Care", "Lip Care", "Sun Care"];

export const dummyRatingsData: Rating[] = [
    { id: "rat_1", rating: 4.2, review: "I was a bit skeptical at first about the snail mucin, but this essence turned out to be even better than I imagined. My skin feels so hydrated and the texture has improved significantly. I've already recommended it to friends and will definitely purchase again.", user: { name: 'Kristin Watson', image: profile_pic1 }, productId: "prod_1", createdAt: 'Sat Jul 19 2025 14:51:25 GMT+0530 (India Standard Time)', updatedAt: 'Sat Jul 19 2025 14:51:25 GMT+0530 (India Standard Time)', product: { name: 'COSRX Advanced Snail 96 Mucin Power Essence', category:'Skincare', id:'prod_1'} },
    { id: "rat_2", rating: 5.0, review: "This serum is amazing! My skin has never looked better. The green tea scent is refreshing and it absorbs quickly without feeling greasy. Perfect for my combination skin.", user: { name: 'Jenny Wilson', image: profile_pic2 }, productId: "prod_2", createdAt: 'Sat Jul 19 2025 14:51:25 GMT+0530 (India Standard Time)', updatedAt: 'Sat Jul 19 2025 14:51:25 GMT+0530 (India Standard Time)', product: { name: 'Innisfree Green Tea Seed Serum', category:'Skincare', id:'prod_2'} },
    { id: "rat_3", rating: 4.1, review: "The pimple patches work wonders! I put them on overnight and by morning the blemish is significantly reduced. A must-have for anyone with occasional breakouts.", user: { name: 'Bessie Cooper', image: profile_pic3 }, productId: "prod_3", createdAt: 'Sat Jul 19 2025 14:51:25 GMT+0530 (India Standard Time)', updatedAt: 'Sat Jul 19 2025 14:51:25 GMT+0530 (India Standard Time)', product: { name: 'COSRX Acne Pimple Master Patch', category:'Skincare', id:'prod_3'} },
    { id: "rat_4", rating: 5.0, review: "I've tried many sleeping masks but Laneige is by far the best. I wake up with plump, glowing skin every morning. Worth every penny!", user: { name: 'Kristin Watson', image: profile_pic1 }, productId: "prod_4", createdAt: 'Sat Jul 19 2025 14:51:25 GMT+0530 (India Standard Time)', updatedAt: 'Sat Jul 19 2025 14:51:25 GMT+0530 (India Standard Time)', product: { name: 'Laneige Water Sleeping Mask', category:'Skincare', id:'prod_4'} },
    { id: "rat_5", rating: 4.3, review: "Overall, I'm very happy with this purchase. The Dynasty Cream feels luxurious and has helped even out my skin tone. The only reason I didn't give it five stars is because the jar is a bit small for the price. Still, highly recommend it!", user: { name: 'Jenny Wilson', image: profile_pic2 }, productId: "prod_5", createdAt: 'Sat Jul 19 2025 14:51:25 GMT+0530 (India Standard Time)', updatedAt: 'Sat Jul 19 2025 14:51:25 GMT+0530 (India Standard Time)', product: { name: 'Beauty of Joseon Dynasty Cream', category:'Skincare', id:'prod_5'} },
    { id: "rat_6", rating: 5.0, review: "This toner has transformed my skin! The AHA-BHA-PHA formula is gentle yet effective. My textured skin is now smooth and clear. Thank you Some By Mi!", user: { name: 'Bessie Cooper', image: profile_pic3 }, productId: "prod_6", createdAt: 'Sat Jul 19 2025 14:51:25 GMT+0530 (India Standard Time)', updatedAt: 'Sat Jul 19 2025 14:51:25 GMT+0530 (India Standard Time)', product: { name: 'Some By Mi AHA-BHA-PHA 30 Days Miracle Toner', category:'Skincare', id:'prod_6'} },
]

export const dummyStoreData: Store = {
    id: "cmemkqnzm000htat8u7n8cpte",
    userId: "user_1",
    name: "Happy Shop",
    description: "At KoreaBeauty Hub, we specialize in bringing you the finest Korean cosmetics and beauty products. From premium skincare to innovative makeup, we connect Kenyan businesses with authentic Korean beauty manufacturers for wholesale and retail opportunities.",
    username: "happyshop",
    address: "3rd Floor, Happy Shop , New Building, 123 street , c sector , NY, US",
    status: "approved",
    isActive: true,
    logo: happy_store,
    email: "happyshop@example.com",
    contact: "+0 1234567890",
    createdAt: "2025-09-04T09:04:16.189Z",
    updatedAt: "2025-09-04T09:04:44.273Z",
    user: {
        id: "user_31dOriXqC4TATvc0brIhlYbwwc5",
        name: "Admin User",
        email: "admin@koreabeautyhub.com",
        image: gs_logo,
    }
}

export const productDummyData: Product[] = [
    {
        id: "prod_1",
        name: "COSRX Advanced Snail 96 Mucin Power Essence",
        description: "Lightweight essence with 96% snail mucin extract for intense hydration and skin repair. Perfect for dry and sensitive skin types. This bestselling Korean serum delivers visible results within weeks.",
        mrp: 4500,
        price: 3500,
        images: [essence, anna_keibalo, elena_soroka],
        category: "Skincare",
        storeId: "cmemkqnzm000htat8u7n8cpte",
        inStock: true,
        store: dummyStoreData,
        rating: dummyRatingsData,
        createdAt: 'Sat Jul 29 2025 14:51:25 GMT+0530 (India Standard Time)',
        updatedAt: 'Sat Jul 29 2025 14:51:25 GMT+0530 (India Standard Time)',
        brand: "COSRX",
        size: "100 ml",
        formula: "Lightweight, fast-absorbing essence with 96% snail secretion filtrate",
        howToUse: "1. After cleansing and toning\n2. Apply a few drops to face\n3. Gently pat for absorption\n4. Follow with moisturizer",
        keyBenefits: ["🐌 96% snail mucin for skin repair", "💧 Intense hydration", "✨ Improves skin texture", "🌟 Fades acne scars"],
        keyIngredients: ["Snail Secretion Filtrate (96%)", "Niacinamide", "Betaine"],
        skinTypes: "All skin types",
        skinConcerns: "Dryness, Scars, Texture, Aging",
        texture: "Lightweight essence"
    },
    {
        id: "prod_2",
        name: "COSRX Acne Pimple Master Patch",
        description: "Hydrocolloid patches that protect pimples and absorb impurities. 24 patches per pack. Perfect for overnight blemish treatment and preventing picking.",
        mrp: 1200,
        price: 950,
        images: [anna_keibalo],
        storeId: "cmemkqnzm000htat8u7n8cpte",
        inStock: true,
        store: dummyStoreData,
        category: "Skincare",
        rating: dummyRatingsData,
        createdAt: 'Sat Jul 28 2025 14:51:25 GMT+0530 (India Standard Time)',
        updatedAt: 'Sat Jul 28 2025 14:51:25 GMT+0530 (India Standard Time)',
        brand: "COSRX",
        size: "24 patches",
        formula: "Hydrocolloid dressing patches",
        howToUse: "1. Cleanse the affected area\n2. Select patch size\n3. Apply to pimple\n4. Leave for 8-12 hours",
        keyBenefits: ["🛡️ Protects from bacteria", "💨 Absorbs impurities", "⏱️ Overnight treatment", "🚫 Prevents picking"],
        keyIngredients: ["Cellulose Gum", "Polyisobutene", "Styrene/Isoprene Copolymer"],
        skinTypes: "Acne-prone, Oily, Combination",
        skinConcerns: "Acne, Pimples, Breakouts",
        texture: "Adhesive patches"
    },
    {
        id: "prod_3",
        name: "Innisfree Green Tea Seed Serum",
        description: "Hydrating serum with Jeju green tea extract and green tea seed oil for deep moisture. Provides 24-hour hydration and strengthens skin barrier.",
        mrp: 4200,
        price: 3200,
        images: [elena_soroka, maria_lupan],
        storeId: "cmemkqnzm000htat8u7n8cpte",
        inStock: true,
        store: dummyStoreData,
        category: "Skincare",
        rating: dummyRatingsData,
        createdAt: 'Sat Jul 27 2025 14:51:25 GMT+0530 (India Standard Time)',
        updatedAt: 'Sat Jul 27 2025 14:51:25 GMT+0530 (India Standard Time)',
        brand: "Innisfree",
        size: "50 ml",
        formula: "Watery serum with green tea seed oil",
        howToUse: "1. Use after toner\n2. Apply 2-3 drops\n3. Gently massage\n4. Pat for absorption",
        keyBenefits: ["🍃 24-hour hydration", "🛡️ Strengthens skin barrier", "🌱 Organic green tea", "💧 Non-sticky finish"],
        keyIngredients: ["Green Tea Seed Oil", "Green Tea Extract", "Panthenol"],
        skinTypes: "All skin types",
        skinConcerns: "Dryness, Dullness, Weak barrier",
        texture: "Watery serum"
    },
    {
        id: "prod_4",
        name: "Laneige Water Sleeping Mask",
        description: "Overnight sleeping mask that intensely hydrates and brightens skin while you sleep. Features patented MoistureWrap technology for glowing morning skin.",
        mrp: 4800,
        price: 3800,
        images: [maria_lupan, valeriia_miller],
        storeId: "cmemkqnzm000htat8u7n8cpte",
        inStock: true,
        store: dummyStoreData,
        category: "Skincare",
        rating: dummyRatingsData,
        createdAt: 'Sat Jul 26 2025 14:51:25 GMT+0530 (India Standard Time)',
        updatedAt: 'Sat Jul 26 2025 14:51:25 GMT+0530 (India Standard Time)',
        brand: "Laneige",
        size: "70 ml",
        formula: "Gel-type sleeping mask with MoistureWrap technology",
        howToUse: "1. Apply as last step of night routine\n2. Spread evenly\n3. Leave on overnight\n4. Rinse in morning",
        keyBenefits: ["😴 Overnight hydration", "✨ Brightens skin", "🌟 MoistureWrap technology", "💧 Wake up glowing"],
        keyIngredients: ["Squalane", "Hydro Ion Mineral Water", "Butylene Glycol"],
        skinTypes: "All skin types",
        skinConcerns: "Dryness, Dullness, Dehydration",
        texture: "Cooling gel"
    },
    {
        id: "prod_5",
        name: "Beauty of Joseon Dynasty Cream",
        description: "Luxurious cream with rice bran water and ginseng extract for radiant skin. Traditional Korean hanbang ingredients meet modern skincare science.",
        mrp: 5200,
        price: 4200,
        images: [valeriia_miller, essence, anna_keibalo],
        storeId: "cmemkqnzm000htat8u7n8cpte",
        inStock: true,
        store: dummyStoreData,
        category: "Skincare",
        rating: [...dummyRatingsData,...dummyRatingsData],
        createdAt: 'Sat Jul 25 2025 14:51:25 GMT+0530 (India Standard Time)',
        updatedAt: 'Sat Jul 25 2025 14:51:25 GMT+0530 (India Standard Time)',
        brand: "Beauty of Joseon",
        size: "50 ml",
        formula: "Rich cream with hanbang ingredients",
        howToUse: "1. Apply as final step\n2. Take small amount\n3. Massage gently\n4. Focus on dry areas",
        keyBenefits: ["🍚 Rice bran water", "🌿 Ginseng extract", "✨ Radiant glow", "🏛️ Traditional formula"],
        keyIngredients: ["Rice Bran Water", "Ginseng Extract", "Squalane"],
        skinTypes: "Dry, Normal, Combination",
        skinConcerns: "Dullness, Dryness, Aging",
        texture: "Rich cream"
    },
    {
        id: "prod_6",
        name: "Some By Mi AHA-BHA-PHA 30 Days Miracle Toner",
        description: "Exfoliating toner with tea tree water and three types of acids for clear skin. The perfect solution for acne-prone and textured skin.",
        mrp: 3500,
        price: 2800,
        images: [essence, elena_soroka],
        storeId: "cmemkqnzm000htat8u7n8cpte",
        inStock: true,
        store: dummyStoreData,
        category: "Skincare",
        rating: [...dummyRatingsData,...dummyRatingsData],
        createdAt: 'Sat Jul 25 2025 14:51:25 GMT+0530 (India Standard Time)',
        updatedAt: 'Sat Jul 25 2025 14:51:25 GMT+0530 (India Standard Time)',
        brand: "Some By Mi",
        size: "150 ml",
        formula: "Exfoliating toner with AHA, BHA, PHA",
        howToUse: "1. After cleansing\n2. Soak cotton pad\n3. Wipe gently\n4. Pat to absorb",
        keyBenefits: ["🍃 Tea tree water", "⚡ Triple acids", "🌟 Clear skin", "🔄 30-day miracle"],
        keyIngredients: ["Tea Tree Water", "AHA", "BHA", "PHA", "Niacinamide"],
        skinTypes: "Oily, Combination, Acne-prone",
        skinConcerns: "Acne, Texture, Large pores",
        texture: "Watery toner"
    },
    {
        id: "prod_7",
        name: "Etude House Drawing Eyebrow Pencil",
        description: "Easy-to-use eyebrow pencil with triangular tip for natural-looking brows. Long-lasting formula that stays put all day.",
        mrp: 1500,
        price: 1200,
        images: [anna_keibalo, maria_lupan],
        storeId: "cmemkqnzm000htat8u7n8cpte",
        inStock: true,
        store: dummyStoreData,
        category: "Makeup",
        rating: [...dummyRatingsData,...dummyRatingsData],
        createdAt: 'Sat Jul 24 2025 14:51:25 GMT+0530 (India Standard Time)',
        updatedAt: 'Sat Jul 24 2025 14:51:25 GMT+0530 (India Standard Time)',
        brand: "Etude House",
        size: "0.3 g",
        formula: "Auto eyebrow pencil with triangular tip",
        howToUse: "1. Brush eyebrows upward\n2. Draw with pencil\n3. Blend with spoolie\n4. Set with brow mascara",
        keyBenefits: ["✏️ Triangular tip", "💧 Long-lasting", "🎨 Natural look", "🖌️ Built-in brush"],
        keyIngredients: ["Iron Oxides", "Stearic Acid", "Hydrogenated Castor Oil"],
        skinTypes: "All skin types",
        skinConcerns: "Sparse brows, Uneven shape",
        texture: "Creamy pencil"
    },
    {
        id: "prod_8",
        name: "Laneige Lip Sleeping Mask Berry",
        description: "Leave-on lip mask that soothes and moisturizes with berry mix complex. Wake up to soft, supple lips every morning.",
        mrp: 2800,
        price: 2200,
        images: [elena_soroka, valeriia_miller],
        storeId: "cmemkqnzm000htat8u7n8cpte",
        inStock: true,
        store: dummyStoreData,
        category: "Lip Care",
        rating: [...dummyRatingsData,...dummyRatingsData],
        createdAt: 'Sat Jul 23 2025 14:51:25 GMT+0530 (India Standard Time)',
        updatedAt: 'Sat Jul 23 2025 14:51:25 GMT+0530 (India Standard Time)',
        brand: "Laneige",
        size: "20 g",
        formula: "Berry mix complex lip mask",
        howToUse: "1. Apply generous layer at night\n2. Leave on overnight\n3. Wipe or rinse in morning",
        keyBenefits: ["🍓 Berry complex", "💧 Intense moisture", "😴 Overnight treatment", "🌟 Soft lips"],
        keyIngredients: ["Berry Mix Complex", "Vitamin C", "Hyaluronic Acid"],
        skinTypes: "All lip types",
        skinConcerns: "Dry lips, Chapped lips, Dullness",
        texture: "Balm texture"
    },
    {
        id: "prod_9",
        name: "Innisfree Super Volcanic Pore Clay Mask",
        description: "Pore clearing clay mask with Jeju volcanic clusters absorbs excess oil and impurities. Minimizes the appearance of pores.",
        mrp: 3200,
        price: 2600,
        images: [maria_lupan, essence],
        storeId: "cmemkqnzm000htat8u7n8cpte",
        inStock: true,
        store: dummyStoreData,
        category: "Skincare",
        rating: [...dummyRatingsData,...dummyRatingsData],
        createdAt: 'Sat Jul 22 2025 14:51:25 GMT+0530 (India Standard Time)',
        updatedAt: 'Sat Jul 22 2025 14:51:25 GMT+0530 (India Standard Time)',
        brand: "Innisfree",
        size: "100 ml",
        formula: "Volcanic clay mask with Jeju volcanic clusters",
        howToUse: "1. Apply to clean face\n2. Avoid eye area\n3. Leave 15 minutes\n4. Rinse thoroughly",
        keyBenefits: ["🌋 Volcanic clusters", "🧹 Clears pores", "💨 Controls oil", "✨ Smooth texture"],
        keyIngredients: ["Jeju Volcanic Cluster Spheres", "Kaolin", "Bentonite"],
        skinTypes: "Oily, Combination, Acne-prone",
        skinConcerns: "Large pores, Excess oil, Impurities",
        texture: "Clay mask"
    },
    {
        id: "prod_10",
        name: "Beauty of Joseon Glow Serum Propolis + Niacinamide",
        description: "Brightening serum with propolis extract and niacinamide for glowing skin. Perfect for achieving that Korean glass skin look.",
        mrp: 4000,
        price: 3200,
        images: [valeriia_miller, anna_keibalo],
        storeId: "cmemkqnzm000htat8u7n8cpte",
        inStock: true,
        store: dummyStoreData,
        category: "Skincare",
        rating: [...dummyRatingsData,...dummyRatingsData],
        createdAt: 'Sat Jul 21 2025 14:51:25 GMT+0530 (India Standard Time)',
        updatedAt: 'Sat Jul 21 2025 14:51:25 GMT+0530 (India Standard Time)',
        brand: "Beauty of Joseon",
        size: "30 ml",
        formula: "Propolis and niacinamide brightening serum",
        howToUse: "1. Use after toner\n2. Apply 2-3 drops\n3. Gently pat\n4. Follow with moisturizer",
        keyBenefits: ["🍯 Propolis extract", "✨ Niacinamide glow", "🌟 Glass skin", "💧 Brightening effect"],
        keyIngredients: ["Propolis Extract", "Niacinamide", "Sea Buckthorn Extract"],
        skinTypes: "All skin types",
        skinConcerns: "Dullness, Dark spots, Uneven tone",
        texture: "Lightweight serum"
    },
    {
        id: "prod_11",
        name: "Etude House SoonJung 2x Barrier Intensive Cream",
        description: "Hypoallergenic cream for sensitive skin with panthenol and madecassoside. Soothes and strengthens skin barrier without irritation.",
        mrp: 3000,
        price: 2400,
        images: [essence, elena_soroka],
        storeId: "cmemkqnzm000htat8u7n8cpte",
        inStock: true,
        store: dummyStoreData,
        category: "Skincare",
        rating: [...dummyRatingsData,...dummyRatingsData],
        createdAt: 'Sat Jul 20 2025 14:51:25 GMT+0530 (India Standard Time)',
        updatedAt: 'Sat Jul 20 2025 14:51:25 GMT+0530 (India Standard Time)',
        brand: "Etude House",
        size: "75 ml",
        formula: "Hypoallergenic cream with panthenol",
        howToUse: "1. Apply as final step\n2. Gently massage\n3. Focus on sensitive areas",
        keyBenefits: ["🌿 Hypoallergenic", "🛡️ Barrier care", "🌸 Panthenol soothing", "💧 Gentle formula"],
        keyIngredients: ["Panthenol", "Madecassoside", "Green Tea Extract"],
        skinTypes: "Sensitive, Dry, Normal",
        skinConcerns: "Sensitivity, Weak barrier, Redness",
        texture: "Soft cream"
    },
    {
        id: "prod_12",
        name: "Some By Mi Snail Truecica Miracle Repair Serum",
        description: "Repair serum with black snail mucin and Truecica for damaged skin barrier. Ideal for acne scars and sensitive skin recovery.",
        mrp: 4500,
        price: 3600,
        images: [anna_keibalo],
        storeId: "cmemkqnzm000htat8u7n8cpte",
        inStock: true,
        store: dummyStoreData,
        category: "Skincare",
        rating: [...dummyRatingsData,...dummyRatingsData],
        createdAt: 'Sat Jul 19 2025 14:51:25 GMT+0530 (India Standard Time)',
        updatedAt: 'Sat Jul 19 2025 14:51:25 GMT+0530 (India Standard Time)',
        brand: "Some By Mi",
        size: "50 ml",
        formula: "Black snail mucin with Truecica complex",
        howToUse: "1. Use after toner\n2. Apply few drops\n3. Gently massage\n4. Pat for absorption",
        keyBenefits: ["🐌 Black snail mucin", "🌿 Truecica complex", "✨ Scar repair", "🛡️ Barrier recovery"],
        keyIngredients: ["Black Snail Mucin", "Truecica", "Tea Tree Extract"],
        skinTypes: "All skin types",
        skinConcerns: "Acne scars, Sensitivity, Damaged barrier",
        texture: "Lightweight serum"
    },
    {
        id: "prod_13",
        name: "Korean Beauty Model Anna Collection",
        description: "Premium Korean cosmetics set featuring Anna Keibalo's favorite products for flawless skin. Complete routine for glass skin effect.",
        mrp: 12000,
        price: 9500,
        images: [anna_keibalo, elena_soroka, maria_lupan],
        category: "Skincare",
        storeId: "cmemkqnzm000htat8u7n8cpte",
        inStock: true,
        store: dummyStoreData,
        rating: dummyRatingsData,
        createdAt: 'Sat Jul 18 2025 14:51:25 GMT+0530 (India Standard Time)',
        updatedAt: 'Sat Jul 18 2025 14:51:25 GMT+0530 (India Standard Time)',
        brand: "KoreaBeauty Hub",
        size: "Full set",
        formula: "Complete skincare routine set",
        howToUse: "Complete morning and night routine included",
        keyBenefits: ["👤 Model curated", "✨ Glass skin", "🌟 Complete routine", "💎 Premium quality"],
        keyIngredients: ["Varied by product - full ingredient list included"],
        skinTypes: "All skin types",
        skinConcerns: "Overall skin health, Radiance",
        texture: "Various textures"
    },
    {
        id: "prod_14",
        name: "Elena Soroka K-Beauty Essentials",
        description: "Curated collection by Elena Soroka featuring must-have Korean beauty products for natural, glowing skin.",
        mrp: 8500,
        price: 6800,
        images: [elena_soroka, maria_lupan, valeriia_miller],
        category: "Skincare",
        storeId: "cmemkqnzm000htat8u7n8cpte",
        inStock: true,
        store: dummyStoreData,
        rating: dummyRatingsData,
        createdAt: 'Sat Jul 17 2025 14:51:25 GMT+0530 (India Standard Time)',
        updatedAt: 'Sat Jul 17 2025 14:51:25 GMT+0530 (India Standard Time)',
        brand: "KoreaBeauty Hub",
        size: "Essential set",
        formula: "Essential beauty collection",
        howToUse: "Daily routine guide included",
        keyBenefits: ["🌿 Natural glow", "👤 Model approved", "💧 Hydration focus", "🌸 Gentle care"],
        keyIngredients: ["Natural Korean extracts"],
        skinTypes: "Normal, Combination, Dry",
        skinConcerns: "Natural radiance, Hydration",
        texture: "Various textures"
    },
    {
        id: "prod_15",
        name: "Maria Lupan Premium K-Beauty Set",
        description: "Luxury Korean cosmetics collection selected by Maria Lupan for premium skincare experience and visible results.",
        mrp: 15000,
        price: 12000,
        images: [maria_lupan, essence, valeriia_miller],
        category: "Skincare",
        storeId: "cmemkqnzm000htat8u7n8cpte",
        inStock: true,
        store: dummyStoreData,
        rating: dummyRatingsData,
        createdAt: 'Sat Jul 16 2025 14:51:25 GMT+0530 (India Standard Time)',
        updatedAt: 'Sat Jul 16 2025 14:51:25 GMT+0530 (India Standard Time)',
        brand: "KoreaBeauty Hub",
        size: "Luxury set",
        formula: "Premium luxury collection",
        howToUse: "Premium routine instructions included",
        keyBenefits: ["💎 Luxury experience", "👤 Premium selection", "✨ Visible results", "🌟 Anti-aging focus"],
        keyIngredients: ["Premium Korean botanicals"],
        skinTypes: "All skin types",
        skinConcerns: "Aging, Luxury care, Overall wellness",
        texture: "Premium textures"
    },
    {
        id: "prod_16",
        name: "Valeriia Miller Modern K-Beauty Collection",
        description: "Contemporary Korean beauty essentials curated by Valeriia Miller for modern, effective skincare routines.",
        mrp: 10000,
        price: 8000,
        images: [valeriia_miller, elena_soroka, anna_keibalo],
        category: "Skincare",
        storeId: "cmemkqnzm000htat8u7n8cpte",
        inStock: true,
        store: dummyStoreData,
        rating: dummyRatingsData,
        createdAt: 'Sat Jul 15 2025 14:51:25 GMT+0530 (India Standard Time)',
        updatedAt: 'Sat Jul 15 2025 14:51:25 GMT+0530 (India Standard Time)',
        brand: "KoreaBeauty Hub",
        size: "Modern collection",
        formula: "Modern K-beauty formulas",
        howToUse: "Modern routine guide included",
        keyBenefits: ["🔬 Modern formulas", "👤 Contemporary style", "⚡ Fast results", "🌱 Clean ingredients"],
        keyIngredients: ["Modern Korean innovations"],
        skinTypes: "All skin types",
        skinConcerns: "Modern skin concerns, Efficiency",
        texture: "Modern textures"
    }
];

export const ourSpecsData = [
    { title: "Free Shipping", description: "Enjoy fast, free delivery on every order no conditions, just reliable doorstep.", icon: SendIcon, accent: '#05DF72' },
    { title: "7 Days easy Return", description: "Change your mind? No worries. Return any item within 7 days.", icon: ClockFadingIcon, accent: '#FF8904' },
    { title: "24/7 Customer Support", description: "We're here for you. Get expert help with our customer support.", icon: HeadsetIcon, accent: '#A684FF' }
]

export const addressDummyData: Address = {
    id: "addr_1",
    userId: "user_1",
    name: "John Doe",
    email: "johndoe@example.com",
    street: "123 Main St",
    city: "New York",
    state: "NY",
    zip: "10001",
    country: "USA",
    phone: "1234567890",
    createdAt: 'Sat Jul 19 2025 14:51:25 GMT+0530 (India Standard Time)',
}

export const couponDummyData: Coupon[] = [
    { code: "NEW20", description: "20% Off for New Users", discount: 20, forNewUser: true, forMember: false, isPublic: false, expiresAt: "2026-12-31T00:00:00.000Z", createdAt: "2025-08-22T08:35:31.183Z" },
    { code: "NEW10", description: "10% Off for New Users", discount: 10, forNewUser: true, forMember: false, isPublic: false, expiresAt: "2026-12-31T00:00:00.000Z", createdAt: "2025-08-22T08:35:50.653Z" },
    { code: "OFF20", description: "20% Off for All Users", discount: 20, forNewUser: false, forMember: false, isPublic: false, expiresAt: "2026-12-31T00:00:00.000Z", createdAt: "2025-08-22T08:42:00.811Z" },
    { code: "OFF10", description: "10% Off for All Users", discount: 10, forNewUser: false, forMember: false, isPublic: false, expiresAt: "2026-12-31T00:00:00.000Z", createdAt: "2025-08-22T08:42:21.279Z" },
    { code: "PLUS10", description: "20% Off for Members", discount: 10, forNewUser: false, forMember: true, isPublic: false, expiresAt: "2027-03-06T00:00:00.000Z", createdAt: "2025-08-22T11:38:20.194Z" }
]

export const dummyUserData: User = {
    id: "user_31dQbH27HVtovbs13X2cmqefddM",
    name: "Admin User",
    email: "admin@koreabeautyhub.com",
    image: gs_logo,
    cart: {}
}

export const orderDummyData: Order[] = [
    {
        id: "cmemm75h5001jtat89016h1p3",
        total: 214.2,
        status: "DELIVERED",
        userId: "user_31dQbH27HVtovbs13X2cmqefddM",
        storeId: "cmemkqnzm000htat8u7n8cpte",
        addressId: "cmemm6g95001ftat8omv9b883",
        isPaid: false,
        paymentMethod: "COD",
        createdAt: "2025-08-22T09:15:03.929Z",
        updatedAt: "2025-08-22T09:15:50.723Z",
        isCouponUsed: true,
        coupon: dummyRatingsData[2],
        orderItems: [
            { orderId: "cmemm75h5001jtat89016h1p3", productId: "cmemlydnx0017tat8h3rg92hz", quantity: 1, price: 89, product: productDummyData[0], },
            { orderId: "cmemm75h5001jtat89016h1p3", productId: "cmemlxgnk0015tat84qm8si5v", quantity: 1, price: 149, product: productDummyData[1], }
        ],
        address: addressDummyData,
        user: dummyUserData
    },
    {
        id: "cmemm6jv7001htat8vmm3gxaf",
        total: 421.6,
        status: "DELIVERED",
        userId: "user_31dQbH27HVtovbs13X2cmqefddM",
        storeId: "cmemkqnzm000htat8u7n8cpte",
        addressId: "cmemm6g95001ftat8omv9b883",
        isPaid: false,
        paymentMethod: "COD",
        createdAt: "2025-08-22T09:14:35.923Z",
        updatedAt: "2025-08-22T09:15:52.535Z",
        isCouponUsed: true,
        coupon: couponDummyData[0],
        orderItems: [
            { orderId: "cmemm6jv7001htat8vmm3gxaf", productId: "cmemm1f3y001dtat8liccisar", quantity: 1, price: 229, product: productDummyData[2], },
            { orderId: "cmemm6jv7001htat8vmm3gxaf", productId: "cmemm0nh2001btat8glfvhry1", quantity: 1, price: 99, product: productDummyData[3], },
            { orderId: "cmemm6jv7001htat8vmm3gxaf", productId: "cmemlz8640019tat8kz7emqca", quantity: 1, price: 199, product: productDummyData[4], }
        ],
        address: addressDummyData,
        user: dummyUserData
    }
]

export const storesDummyData: Store[] = [
    {
        id: "cmemkb98v0001tat8r1hiyxhn",
        userId: "user_31dOriXqC4TATvc0brIhlYbwwc5",
        name: "KoreaBeauty Store",
        description: "Premium Korean cosmetics wholesale and retail store in Kenya",
        username: "koreabeautystore",
        address: "123 Kimathi Street, Nairobi, Kenya",
        status: "approved",
        isActive: true,
        logo: gs_logo,
        email: "store@koreabeautyhub.com",
        contact: "+254 712 345 678",
        createdAt: "2025-08-22T08:22:16.189Z",
        updatedAt: "2025-08-22T08:22:44.273Z",
        user: dummyUserData,
    },
    {
        id: "cmemkqnzm000htat8u7n8cpte",
        userId: "user_31dQbH27HVtovbs13X2cmqefddM",
        name: "Happy Shop",
        description: "At KoreaBeauty Hub, we specialize in bringing you the finest Korean cosmetics and beauty products. From premium skincare to innovative makeup, we connect Kenyan businesses with authentic Korean beauty manufacturers for wholesale and retail opportunities.",
        username: "happyshop",
        address: "3rd Floor, Happy Shop , New Building, 123 street , c sector , NY, US",
        status: "approved",
        isActive: true,
        logo: happy_store,
        email: "happyshop@example.com",
        contact: "+0 123456789",
        createdAt: "2025-08-22T08:34:15.155Z",
        updatedAt: "2025-08-22T08:34:47.162Z",
        user: dummyUserData,
    }
]

export const dummyAdminDashboardData = {
    "orders": 6,
    "stores": 2,
    "products": 12,
    "revenue": "959.10",
    "allOrders": [
        { "createdAt": "2025-08-20T08:46:58.239Z", "total": 145.6 },
        { "createdAt": "2025-08-22T08:46:21.818Z", "total": 97.2 },
        { "createdAt": "2025-08-22T08:45:59.587Z", "total": 54.4 },
        { "createdAt": "2025-08-23T09:15:03.929Z", "total": 214.2 },
        { "createdAt": "2025-08-23T09:14:35.923Z", "total": 421.6 },
        { "createdAt": "2025-08-23T11:44:29.713Z", "total": 26.1 },
        { "createdAt": "2025-08-24T09:15:03.929Z", "total": 214.2 },
        { "createdAt": "2025-08-24T09:14:35.923Z", "total": 421.6 },
        { "createdAt": "2025-08-24T11:44:29.713Z", "total": 26.1 },
        { "createdAt": "2025-08-24T11:56:29.713Z", "total": 36.1 },
        { "createdAt": "2025-08-25T11:44:29.713Z", "total": 26.1 },
        { "createdAt": "2025-08-25T09:15:03.929Z", "total": 214.2 },
        { "createdAt": "2025-08-25T09:14:35.923Z", "total": 421.6 },
        { "createdAt": "2025-08-25T11:44:29.713Z", "total": 26.1 },
        { "createdAt": "2025-08-25T11:56:29.713Z", "total": 36.1 },
        { "createdAt": "2025-08-25T11:30:29.713Z", "total": 110.1 }
    ]
}

export const dummyStoreDashboardData = {
    "ratings": dummyRatingsData,
    "totalOrders": 2,
    "totalEarnings": 636,
    "totalProducts": 5
}
